/* @LICENSE(NICTA_CORE) */ 

/* This header was generated by kernel/tools/syscall_header_gen.py.
 *
 * To add a system call number, edit kernel/include/api/syscall.xml
 *
 * Generated on <module 'datetime' from '/usr/lib/python2.7/lib-dynload/datetime.so'>.
 *
 */
#ifndef __LIBSEL4_SYSCALL_H
#define __LIBSEL4_SYSCALL_H

enum syscall {
    seL4_SysCall = -1,
    seL4_SysReplyWait = -2,
    seL4_SysSend = -3,
    seL4_SysNBSend = -4,
    seL4_SysWait = -5,
    seL4_SysReply = -6,
    seL4_SysPoll = -7,
    seL4_SysYield = -8,
#ifdef DEBUG
    seL4_SysDebugPutChar = -9,
    seL4_SysDebugHalt = -10,
    seL4_SysDebugCapIdentify = -11,
    seL4_SysDebugSnapshot = -12,
#endif /* DEBUG */
#ifdef DANGEROUS_CODE_INJECTION
    seL4_SysDebugRun = -13,
#endif /* DANGEROUS_CODE_INJECTION */
#ifdef CONFIG_BENCHMARK
    seL4_SysBenchmarkResetLog = -14,
    seL4_SysBenchmarkDumpLog = -15,
    seL4_SysBenchmarkLogSize = -16,
#endif /* CONFIG_BENCHMARK */
    SEL4_FORCE_LONG_ENUM(seL4_Syscall_ID)
} seL4_Syscall_ID;

#endif /* __ARCH_API_SYSCALL_H */
