/* @LICENSE(NICTA_CORE) */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 * Generated on 2013-08-01 15:31:01.852687.
 *
 */
#ifndef __LIBSEL4_ARCH_INVOCATION_H
#define __LIBSEL4_ARCH_INVOCATION_H

enum arch_invocation_label {
    ARMPageTableMap = nInvocationLabels + 0,
    ARMPageTableUnmap = nInvocationLabels + 1,
    ARMPageMap = nInvocationLabels + 2,
    ARMPageRemap = nInvocationLabels + 3,
    ARMPageUnmap = nInvocationLabels + 4,
    ARMPageFlushCaches = nInvocationLabels + 5,
    nArchInvocationLabels
};

#endif /* __LIBSEL4_ARCH_INVOCATION_H */
