#ifndef __SYSCALLS_H__
#define __SYSCALLS_H__

#define NUM_SYSCALLS				18

#define SYSCALL_SBRK	        	(0)

#define SYSCALL_FIND_SERVICE   		(1)
#define SYSCALL_REGISTER_SERVICE	(2)

#define SYSCALL_REGISTER_IRQ		(3)
#define SYSCALL_MAP_DEVICE			(4)

#define SYSCALL_ALLOC_CNODES		(5)
#define SYSCALL_CREATE_EP_SYNC		(6)
#define SYSCALL_CREATE_EP_ASYNC		(7)
#define SYSCALL_BIND_AEP_TCB		(8)

#define SYSCALL_SHARE_CREATE		(9)
#define SYSCALL_SHARE_MOUNT			(10)
#define SYSCALL_SHARE_UNMOUNT		(11)

#define SYSCALL_PROCESS_SUICIDE		(12)
#define SYSCALL_PROCESS_CREATE		(13)
#define SYSCALL_PROCESS_DESTROY		(14)
#define SYSCALL_PROCESS_GETPID		(15)
#define SYSCALL_PROCESS_SEND_STATUS	(16)
#define SYSCALL_PROCESS_WAIT		(17)

#endif