#ifndef __NETWORK_H__
#define __NETWORK_H__

#define NETSVC_SERVICE_REGISTER		(0)
#define NETSVC_SERVICE_UNREGISTER	(1)
#define NETSVC_SERVICE_DATA			(2)

#define NETSVC_PROTOCOL_UDP			(1)
#define NETSVC_PROTOCOL_TCP			(2)

#endif