#define VFS_REGISTER_INFO	(0)
#define VFS_REGISTER_CAP	(1)
#define VFS_MOUNT			(2)
#define VFS_OPEN			(3)
#define VFS_READ			(4)
#define VFS_WRITE			(5)
#define VFS_CLOSE			(6)
#define VFS_LISTDIR			(7)
#define VFS_STAT			(8)
#define VFS_READ_OFFSET		(9)
#define VFS_WRITE_OFFSET	(10)

#define VFS_NUM_EVENTS		(11)