apps-$(CONFIG_APP_SOS) += sos

sos-components-$(CONFIG_APP_SOSH) += sosh
sos-components-$(CONFIG_APP_TTY_TEST) += tty_test
sos-components=$(addprefix $(STAGE_BASE)/bin/, $(sos-components-y))

sos: export COMPONENTS=${sos-components}
sos: ${sos-components-y} \
     libsel4 libsel4elf $(libc) libcpio \
     libsel4cspace libsel4sync libserial libclock \
     liblwip libnfs libethdrivers \
     libsos

