apps-$(CONFIG_APP_SOS) += sos

sos-components-$(CONFIG_APP_SOSH) += sosh
sos-components-$(CONFIG_APP_TTY_TEST) += tty_test
sos-components-$(CONFIG_APP_SOS_TEST) += sos_test

sos-components-$(CONFIG_APP_DEV_CONSOLE) += dev_console
sos-components-$(CONFIG_APP_DEV_TIMER) += dev_timer

sos-components-$(CONFIG_APP_SVC_NETWORK) += svc_network
sos-components-$(CONFIG_APP_SVC_VFS) += svc_vfs

sos-components-$(CONFIG_APP_FS_DEV) += fs_dev

sos-components=$(addprefix $(STAGE_BASE)/bin/, $(sos-components-y))

sos: export COMPONENTS=${sos-components}
sos: ${sos-components-y} \
     libsel4 libsel4elf $(libc) libcpio \
     libsel4cspace libsel4sync libserial libclock \
     liblwip libnfs libethdrivers \
     libsos

